spring:
  datasource:
    username: admin
    password: 1q2w3e4r
    url: jdbc:mysql://portfolio.cobrokkm0djp.ap-northeast-2.rds.amazonaws.com:3306/travel
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: 5jvk3bQ0WwrChdr9u1aJajI8vydU4RG5auz9VOsEekT1zvljnfIigblVXXypuU82